repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint-cli
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: local
    hooks:
      - id: lint-notes
        name: lint-notes
        entry: python scripts/lint_notes.py
        language: system
        pass_filenames: false
