name: CI
on:
  pull_request:
  push:
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      md_only: ${{ steps.filter.outputs.md_only }}
      deps: ${{ steps.filter.outputs.deps }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            md_only:
              - '**/*.md'
            deps:
              - 'requirements.txt'
              - 'package.json'
              - 'package-lock.json'

  secret-check:
    runs-on: ubuntu-latest
    outputs:
      has_pages_token: ${{ steps.echo.outputs.has_pages }}
    steps:
      - id: echo
        run: echo "has_pages=${{ secrets.GH_PAGES_TOKEN != '' }}" >> "$GITHUB_OUTPUT"

  lint-docs:
    needs: [changes]
    if: needs.changes.outputs.md_only == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npx --yes markdownlint-cli '**/*.md'
          grep -R --line-number -E '<{7}|={7}|>{7}' --exclude=ci.yml \
            --exclude-dir=node_modules --exclude-dir=.pre-commit-cache \
            --exclude-dir=frontend/dist --exclude-dir=docs/_build . && exit 1 \
            || echo "No conflict markers"

  markdown-link-check:
    needs: [changes]
    if: needs.changes.outputs.md_only == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: --no-progress --verbose './**/*.md'

  check-versions:
    needs: [changes]
    if: needs.changes.outputs.deps == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make check-versions

  actionlint:
    needs: [changes]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@v1.7.7

  test:
    needs: [changes]
    if: needs.changes.outputs.md_only != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.11', '3.12']
        node: ['20']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Bootstrap
        run: PYTHON_VERSION=${{ matrix.python }} NODE_VERSION=${{ matrix.node }} SKIP_PRECOMMIT=1 ./.codex/setup.sh
      - name: Install Python deps
        run: python -m pip install -r requirements.txt
      - run: make lint
      - run: make typecheck
      - run: make typecheck-ts
      - run: make test
